FIx some broken links
SeldonIO/seldon-core pull request #3341
Opened 2021-06-28 14:11 UTC by zdog234

**What this PR does / why we need it**:

Fixes some broken links in docs

**Special notes for your reviewer**:

Couldn't find good link for _Example model notebooks_

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2021-06-28 14:11 UTC, seldondev commented
Hi @zdog234. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) or [todo](https://github.com/orgs/todo/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/todo/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

2021-06-28 14:11 UTC, seldondev commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/v1.1.0/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["rafalskolasinski"]} -->

2021-07-06 13:05 UTC, majolo requested changes
Made some comments, thanks for your PR

2021-07-06 13:05 UTC, majolo commented on doc/source/python/python_wrapping_s2i.md
> + * [A minimal skeleton for model source code](https://github.com/cliveseldon/seldon-core/tree/master/wrappers/s2i/python/test/model-template-app)
```suggestion
 * [A minimal skeleton for model source code](https://github.com/SeldonIO/seldon-core/tree/master/wrappers/s2i/python/test/model-template-app)
```

2021-07-06 13:05 UTC, majolo commented on doc/source/python/python_wrapping_s2i.md
> + * [Example model notebooks (broken link)](../examples/notebooks.html)
```suggestion
 * [Example model notebooks](../examples/notebooks.rst)
```

2021-07-06 13:05 UTC, majolo commented on doc/source/python/python_wrapping_s2i.md
> + * [A minimal skeleton for router source code](https://github.com/cliveseldon/seldon-core/tree/master/wrappers/s2i/python/test/router-template-app)
Can you replace the other `cliveseldon` fork with `SeldonIO` in this file?

2021-07-12 11:57 UTC, axsaucedo commented
@zdog234 will you  get a chance to have a look at the suggestions?

2021-08-10 10:42 UTC, closed without merging