Inject storage initializer on not prepacked server
SeldonIO/seldon-core pull request #4252
Opened 2022-08-03 05:31 UTC by cnfatal

```release-note
Added Storage Initializers on not prepacked server.
```

**What this PR does / why we need it**:

Enable storage initalizer inject when `modelUri` set in graph on not prepacked server.

**Which issue(s) this PR fixes**: 

Fixes #4251

**Special notes for your reviewer**:

A test already added.

2022-08-03 05:31 UTC, seldondev commented
Hi @cnfatal. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) or [todo](https://github.com/orgs/todo/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/todo/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

2022-08-03 05:39 UTC, seldondev commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["rafalskolasinski"]} -->

2022-08-04 11:36 UTC, axsaucedo commented on operator/controllers/model_initializer_injector.go
> +		// log.Error(err, "Failed to find config map", "name", ControllerConfigMapName)
Why is this commented?

2022-08-04 11:36 UTC, axsaucedo commented on operator/controllers/model_initializer_injector.go
> +		// log.Error(err, "Failed to find config map", "name", ControllerConfigMapName)
Same here

2022-08-04 11:47 UTC, axsaucedo commented on operator/controllers/model_initializer_injector.go
> +	resourceDefaults := []string{
Why are there fmt changes? Is there a version disparity perhaps?

2022-08-04 11:48 UTC, axsaucedo commented on operator/controllers/model_initializer_injector.go
> +	resourceDefaults := []string{
The suggested changes on format look good but best to be added on a separate PR and focus this one on the inject storage initialiser logic

2022-08-04 12:01 UTC, axsaucedo requested changes
Thank you for the contribution @cnfatal , I added a couple of comments. It will be important to keep the PR focused so let's make sure only changes are for the feature, and we can keep format chagnes to a separate PR. It will also be important to make sure we have documentation, and we may also need to add an integration test to ensure this feature is properly supported as it's adding a feature in a key path of the codebase.

2022-08-04 12:04 UTC, axsaucedo commented on operator/controllers/seldondeployment_controller_test.go
> +var _ = Describe("Create a Seldon Deployment with No Engine and graph ModelUri", func() {
Would be good to test also for normal sdep with (multiple) graph node modelUri

2022-08-04 12:30 UTC, RafalSkolasinski commented
Hi @cnfatal, could you post example manifest how you see it being used?

2022-08-08 05:58 UTC, cnfatal commented
> Hi @cnfatal, could you post example manifest how you see it being used?

There are some my cases: https://github.com/SeldonIO/seldon-core/issues/4251#issuecomment-1207699328

2022-08-08 06:07 UTC, cnfatal commented
Hi @axsaucedo  ,It's My fault, I resolved them in a new commit. Could you please have a look once more.

2022-11-05 02:12 UTC, closed without merging