Bugfix consistent pod service monitors reconcilor app labels
SeldonIO/seldon-core pull request #5073
Opened 2023-08-08 18:48 UTC by michaelcheah

**What this PR does / why we need it**:
The default `matchLabel` configs for Prometheus `podmonitor`s do not match what is configured by the `SeldonRuntime` operator for several resources.

This PR:
1. Fixes the labels so that they are consistent across all resources, i.e. all label use `app.kubernetes.io/name` key instead of `app` to reference seldon components
2. The component name `seldon-mesh` is outdated and is updated to `seldon-envoy`.
3. The server metrics port for the default `mlserver` is not defined (it is defined for the `triton` server). We expose it on port 8082 which is the [default](https://mlserver.readthedocs.io/en/latest/reference/settings.html#mlserver.settings.Settings.metrics_port) for `mlserver`

**Which issue(s) this PR fixes**:
Fixes #5071

**Special notes for your reviewer**:

2023-08-09 17:14 UTC, cliveseldon approved these changes

2023-08-09 17:20 UTC, RafalSkolasinski requested changes

2023-08-10 09:34 UTC, RafalSkolasinski commented on prometheus/monitors/pipelinegateway-podmonitor.yaml
> -      app: pipelinegateway
Old labels could be done as in my test [here](https://github.com/RafalSkolasinski/seldon-core/commit/0980b396af5621ab6f65bef2f539f37da05877d9) - I would prefer to have the old labels there as well and then rely on these for metrics.

2023-08-10 14:38 UTC, RafalSkolasinski approved these changes

2023-08-10 15:15 UTC, RafalSkolasinski commented on k8s/helm-charts/seldon-core-v2-setup/templates/seldon-v2-components.yaml
> +      - containerPort: 8082
@michaelcheah did you check that mlserver indeed expose metrics under this port?

2023-08-10 15:16 UTC, RafalSkolasinski commented on k8s/helm-charts/seldon-core-v2-setup/templates/seldon-v2-components.yaml
> +      - containerPort: 8082
Ok, it does.

2023-08-10 15:16 UTC, RafalSkolasinski commented on k8s/helm-charts/seldon-core-v2-setup/templates/seldon-v2-components.yaml
> +      - containerPort: 8082
Ok, it does.

2023-08-10 15:16 UTC, merged