[Update] added a note about deprecation of seldon and tensorflow protocol
SeldonIO/seldon-core pull request #6182
Opened 2024-12-31 08:06 UTC by Rajakavitha1

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

I have note deleted any existing content that explains about Seldon or TensorFlow protocol. Only added a note in the related sections about transitioning to OIP.

2024-12-31 08:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeldonIO/seldon-core?pullRequest=6182) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeldonIO/seldon-core?pullRequest=6182) before we can accept your contribution.<br/><hr/>**Rakavitha Kodhandapani** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeldonIO/seldon-core?pullRequest=6182) it.</sub>

2025-01-04 14:41 UTC, matthewlowdon requested changes
As discussed, remove references to Seldon Protocol and Tensorflow Protocol no longer being supported in Core 1.

2025-01-06 09:54 UTC, Rajakavitha1 commented
> As discussed, remove references to Seldon Protocol and Tensorflow Protocol no longer being supported in Core 1.

Hi @matthewlowdon. I  rephrased the note. Please take a look.

2025-01-13 09:59 UTC, Rajakavitha1 commented
Hi @matthewlowdon and @tchellam I updated the note to include MLServer. Please review.

2025-01-15 10:10 UTC, matthewlowdon requested changes

2025-01-15 10:10 UTC, matthewlowdon commented on doc/source/analytics/explainers.md
> +**Note**: Seldon is no longer maintaining the Seldon and TensorFlow protocols. Instead, Seldon is adopting the industry-standard Open Inference Protocol (OIP). As part of this transition, you need to
I think it would be better to say "has adopted" rather than "is adopting". I also think we should consider not saying they need to use MLServer, as I believe they could use Triton if they wanted. Instead we could link them to MLServer by saying something like "To learn more about the OIP for model serving in Seldon Core 1, please refer to [MLServer]".

2025-01-15 10:10 UTC, matthewlowdon commented on doc/source/graph/protocols.md
>  You can try out the `v2` in [this example notebook](../examples/protocol_examples.html).
Perhaps refer to OIP in addition to V2..? (V2 is the old name for OIP)

2025-01-15 10:10 UTC, matthewlowdon commented on doc/source/graph/protocols.md
> +Activate this protocol by speicfying `protocol: tensorflow` and `transport: rest` or `transport: grpc` in your Seldon Deployment. See [example notebook](../examples/protocol_examples.html).
specifying*

2025-01-15 10:10 UTC, matthewlowdon commented on examples/models/lightgbm_custom_server/iris.ipynb
> +    "   * A KfServing V2 or Open Inference protocol version using MLServer for running lightgbm models\n",
Put OIP first? the other name is outdated and could be put in brackets.

2025-01-16 08:17 UTC, Rajakavitha1 commented on doc/source/analytics/explainers.md
> +**Note**: Seldon is no longer maintaining the Seldon and TensorFlow protocols. Instead, Seldon is adopting the industry-standard Open Inference Protocol (OIP). As part of this transition, you need to
Incorporated the changes suggested.

2025-01-16 08:17 UTC, Rajakavitha1 commented on doc/source/graph/protocols.md
>  You can try out the `v2` in [this example notebook](../examples/protocol_examples.html).
Incorporated the changes suggested.

2025-01-16 08:17 UTC, Rajakavitha1 commented on doc/source/graph/protocols.md
> +Activate this protocol by speicfying `protocol: tensorflow` and `transport: rest` or `transport: grpc` in your Seldon Deployment. See [example notebook](../examples/protocol_examples.html).
Incorporated the changes suggested.

2025-01-16 08:17 UTC, Rajakavitha1 commented on examples/models/lightgbm_custom_server/iris.ipynb
> +    "   * A KfServing V2 or Open Inference protocol version using MLServer for running lightgbm models\n",
Incorporated the changes suggested.

2025-01-17 10:59 UTC, merged